<?php 
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/admin/admin.create.css" />

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<form id="createChallengeForm" class="genericForm" method="<?php echo $this->form['method']?>"  action="<?php echo $this->form['action']?>">
  <div class="createNameElement">
    <label for="name"><?php echo $this->t('Name')?></label>
    <?php echo $this->form['name']?>
  </div>
  <div>
    <label for="description"><?php echo $this->t('Description')?></label>
    <?php echo $this->form['description']?>
  </div>
  <div class="radioElement">
    <h4><?php echo $this->t('Training Status')?></h4>
    <?php echo $this->form['training_status']?>
  </div>
  <div class="radioElement">
    <h4><?php echo $this->t('Testing Status')?></h4>
    <?php echo $this->form['testing_status']?>
  </div>
  <div>
    <input type='submit' name='createChallenge' value='<?php echo $this->t('Create')?>'/>
  </div>
</form>