<?php 
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

echo '<script type="text/javascript" src="' . $this->moduleWebroot . '/public/js/admin/admin.edit.js"></script>';
?>

<form id="editChallengeForm" class="genericForm" method="<?php echo $this->infoForm['method']?>"  action="<?php echo $this->infoForm['action']?>">
  <div class="createNameElement">
    <label for="name"><?php echo $this->t('Name')?></label>
    <?php echo $this->infoForm['name']?>
  </div>
  <div>
    <label for="description"><?php echo $this->t('Description')?></label>
    <?php echo $this->infoForm['description']?>
  </div>
  <div>
    <label for="number_scored_labels"><?php echo $this->t('Number of Scored Labels')?></label>
    <?php echo $this->infoForm['number_scored_labels']?>
  </div>
  <h3>Set Status of Challenge Stages</h3>
  <div class="radioElement">
    <h4><?php echo $this->t('Training Status')?></h4>
    <?php echo $this->infoForm['training_status']?>
  </div>
  <div class="radioElement">
    <h4><?php echo $this->t('Testing Status')?></h4>
    <?php echo $this->infoForm['testing_status']?>
  </div>
  <h3>Select Enabled Metrics</h3>
  <?php
  foreach($this->allMetrics as $metric)
    { ?>
    <div class="radioElement">
      <h4><?php echo $this->t($metric->getMetricName())?></h4>
      <?php echo $this->infoForm[$metric->getMetricExeName()]?>
    </div>
    <?php
    }
  ?>
  
  <div>
    <?php echo $this->infoForm['submit']?>
  </div>
</form>