<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->moduleWebroot . '/public/js/config/config.index.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.browser.js');
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/config/config.index.css" />

<div class="viewMain">
  <h3>Challenge module configuration </h3>
  <img class="tableLoading" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
  <table id="browseTable" class="midasTree">
    <thead>
      <tr>
        <th class="thName">Community</th>
        <th class="thStatus">Can it create a challenge?</th>
        <th class="thCheckbox"><input type="checkbox" id="browseTableHeaderCheckbox" /></th>
      </tr>
    </thead>
    <tbody>
      <?php
      $node=1;
  
      foreach($this->communities as $community)
        {
        echo "<tr id='node--$node' class='' type='community' element='{$community->getCommunityId()}' >";
        echo "  <td class='treeBrowseElement'><span class='community'>{$this->slicename($community->getName(),50)}</span></td>";
        echo "  <td class='challengeCommunityStatus'>";
        echo (in_array($community->getCommunityId(), $this->enabledCommunityIds))? 'Yes':'No';
        echo " </td>";
        echo "  <td><input type='checkbox' class='treeCheckbox' type='community' element='{$community->getCommunityId()}' /></td>";
        echo "</tr>";
        $node++;
        }
      ?>          
       
    </tbody>
  </table>
</div>
<div class="viewSideBar">
    <div>Select one or more communities to enable or disable them to create and own a challenge.</div>
    <div class="sideElementFirst viewAction" style="display:none;">
    <h1>Actions</h1>
    <ul>
      <li>
        
      </li>
    </ul>
  </div>
  <div class="sideElement viewSelected" >
    <h1><?php echo $this->t('Selected')?><span></span></h1>
    <span></span>
  </div>
  <div class="sideElementLast viewInfo" style="display:none;">
    <h1>Info</h1>    
    <img class="infoLoading" style="display:none;" alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif"/>
    <div class="ajaxInfoElement">
    </div>
  </div>
</div>
