<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot . '/public/js/layout/jquery.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.tablesorter.min.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/competitor/competitor.scorelisting.js');
$this->headScript()->appendFile($this->apiWebroot . '/public/js/common/common.ajaxapi.js');
?>


<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.tablesorter.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/competitor/competitor.showscore.css" />


      
<div id="scorelisting" >
    
    <table id="scorelistingtable" class="tablesorter">
      <thead>
        <tr class="header">
        <?php
        foreach($this->tableHeaders as $header)
          {
          echo "<th>".ucfirst($header)."</th>";
          }
        ?>
        </tr>
      </thead>
      <tbody>
          <?php      
            $stripeClasses = array('odd', 'even');
            $stripeClassInd = 0;
            
            foreach($this->scorelistingRows as $scorelistingRow)
              {
              echo "<tr class='resultsRow ".$stripeClasses[$stripeClassInd++ % 2]."'>";
              foreach($this->tableColumns as $column)
                {
                $link = $scorelistingRow[$column]['link'];
                $text = $scorelistingRow[$column]['text'];
                if(!empty($link))
                  {
                  echo "<td><a href=" . $link . ">" . $text . '</a></td>';
                  }
                else
                  {
                  echo '<td>' . $text . '</td>';
                  }
                }
              echo "</tr>";
              }
          ?> 
      </tbody>
    </table>
    <br/>
</div>





