<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
echo '<script type="text/javascript" src="' . $this->apiWebroot . '/public/js/common/common.ajaxapi.js"></script>';
echo '<script type="text/javascript" src="' . $this->coreWebroot. '/public/js/jquery/jquery.tablesorter.min.js"></script>';
echo '<script type="text/javascript" src="' . $this->moduleWebroot. '/public/js/jquery.dataTables.js"></script>';
echo '<script type="text/javascript" src="' . $this->moduleWebroot . '/public/js/competitor/competitor.dashboard.js"></script>';
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.tablesorter.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/jquery.dataTables.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/competitor/competitor.common.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/competitor/competitor.dashboard.css" />
      
<div id="dashboard" >
    <div class="aboutThisPage" id="challengeCompetitorScoreboardAbout"><a>about this page</a></div>
    
<?php if($this->noResults)
        {
        echo "There are no posted results for this challenge.";
        }
      else
        { 
?>
    <table id="challenge_dashboard" style="display:table" class="tablesorter">
        <thead>
          <tr class="header">
          <?php
          echo "<th>Competitor</th>";
          foreach($this->resultColumns as $header)
            {
            $splitHeader = str_replace(' ', '<br/>', $header);
            if(array_key_exists($header, $this->metricIds))
              {
              echo "<th class='scorecol midasChallengeMetricCol' id='challengeMetric_".$this->metricIds[$header]."' >".ucfirst($splitHeader)."</th>";
              }
            else
              {
              echo "<th class='scorecol'>".ucfirst($splitHeader)."</th>";
              }  
            }
          ?>
          </tr>
        </thead>
        <tbody>
          <?php       
            foreach($this->tableData as $competitorId => $scores)
              {
              if(array_key_exists($competitorId, $this->userResultsLinks))
                {
                echo '<tr><td><a href="' . $this->userResultsLinks[$competitorId] .'">'.$competitorId."</td>";
                }
              else
                {
                echo "<tr><td>".$competitorId."</td>";
                }
              foreach($this->resultColumns as $resultColumn)
                {
                $columnData = $scores[$resultColumn];  
                $metricAverage = $columnData['metric_average'];
                $rank = $columnData['rank'];
                if(is_numeric($metricAverage))
                  {
                  $metricAverage = round($metricAverage, MIDAS_CHALLENGE_NUM_ROUNDING_DIGITS);  
                  }
                if(is_numeric($rank))
                  {
                  $rank = round($rank, MIDAS_CHALLENGE_NUM_ROUNDING_DIGITS);  
                  }
                  
                echo "<td>".$metricAverage."<br/>".$rank."</td>";
                }
              echo "</tr>";
              }
          ?> 
        </tbody>
    </table>
    <br/>
<?php
        } // $this->noResults == true
?>
    
    </div>
</div>





