<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
echo '<script type="text/javascript" src="' . $this->apiWebroot . '/public/js/common/common.ajaxapi.js"></script>';
echo '<script type="text/javascript" src="' . $this->coreWebroot . '/public/js/jquery/jquery.dataTable.js"></script>';
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/competitor/competitor.showscore.css" />
      
<div id="showscores" >
  <?php
    foreach($this->tableHeaders as $challengeId => $headers)
      {
      if(!empty($headers))
      {   
      echo "<h4>".$this->challengeInfo[$challengeId]['name']."<h4>";
      //echo '<input type="button" onclick="displayResult("'.$challengeName.'")" value="diaplay scores" />';
      echo '<table id="'.$challengeId.'" style="display:table" class="display">';
  ?>
        <thead>
        <tr class="header">
        <?php
        foreach($headers as $header)
          {
          echo "<th>".ucfirst($header)."</th>";
          }
        ?>
        </tr>
        </thead>
        <tbody>
        <tr>
          <?php       
            foreach($this->tableData[$challengeId] as $competitorId => $scores)
              {
              echo "<tr> <td>".$competitorId."</td>";
              foreach($scores as $column)
                {
                echo "<td>".$column."</td>";
                }
              echo "</tr>";
              }
          ?> 
        </tr>
      </tbody>
    </table>
  <?php
      }
    }
  ?>
</div>





