<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
echo '<script type="text/javascript" src="' . $this->apiWebroot . '/public/js/common/common.ajaxapi.js"></script>';
echo '<script type="text/javascript" src="' . $this->coreWebroot. '/public/js/jquery/jquery.tablesorter.min.js"></script>';
echo '<script type="text/javascript" src="' . $this->moduleWebroot. '/public/js/jquery.dataTables.js"></script>';
echo '<script type="text/javascript" src="' . $this->moduleWebroot . '/public/js/competitor/competitor.dashboard.js"></script>';
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.tablesorter.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/jquery.dataTables.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/competitor/competitor.dashboard.css" />
      
<div id="dashboard" >
  <?php
    foreach($this->tableHeaders as $challengeId => $headers)
      {
      if(!empty($headers))
      {
      echo "<div class='dashboardHeading'> <span>-</span> ".$this->challengeInfo[$challengeId]['name']."</div>";  
      echo '<div class="dashboardContent"> <table id="challenge_dashboard" style="display:table" class="tablesorter">';
  ?>
        <thead>
          <tr class="header">
          <?php
          foreach($headers as $header)
            {
            echo "<th>".ucfirst($header)."</th>";
            }
          ?>
          </tr>
        </thead>
        <tbody>
          <?php       
            foreach($this->tableData[$challengeId] as $competitorId => $scores)
              {
              echo "<tr> <td>".$competitorId."</td>";
              foreach($this->resultColumns as $resultColumn)
                {
                $columnData = $scores[$resultColumn];  
                $metricAverage = $columnData['metric_average'];
                echo "<td>".$metricAverage." ".$columnData['rank']."</td>";
                }
              echo "</tr>";
              }
          ?> 
        </tbody>
    </table>
    <br/>
    </div>
  <?php
      }
    break;  
    }
  ?>
</div>





