<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/competitor/competitor.init.js');
$this->headScript()->appendFile($this->apiWebroot.'/public/js/common/common.ajaxapi.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/competitor/competitor.init.css" />


  <div id="midas_challenge_competitor_init" class="viewMain">
    <?php
      if(!empty($this->challenges))
        {
         echo '
         <table>
         <tr><td><h3>Challenge:</h3></td>
         <td><select id="midas_challenge_competitor_challengeId">';
         $challenge0 = null;
         foreach($this->challenges as $challenge)
           {
           if($challenge0 === null)
             {
             $challenge0 = $challenge;  
             }
           echo '<option value="'.$challenge["id"].'">'.$challenge['name'].'</>';
           }
         echo '</select></td></tr>';
        
         
         echo '
         <tr><td><h3>Dataset:</h3></td>
         <td><select id="midas_challenge_competitor_resultsType">';
         $defaultFolderId = null;
         $defaultFolderName = null;
         if($challenge0['testing_status'] === MIDAS_CHALLENGE_STATUS_OPEN)
           {
           $defaultFolderId = $this->challengeResultsFolders[$challenge0["id"]]['testing_submission_folder_id'];  
           $defaultFolderName = $this->challengeResultsFolders[$challenge0["id"]]['testing_submission_folder_name'];  
           echo '<option value="'.MIDAS_CHALLENGE_TESTING.'">'.MIDAS_CHALLENGE_TESTING.'</>';
           }
         if($challenge0['training_status'] === MIDAS_CHALLENGE_STATUS_OPEN)
           {
           if(!$defaultFolderId)
             {
             $defaultFolderId = $this->challengeResultsFolders[$challenge0["id"]]['training_submission_folder_id'];  
             $defaultFolderName = $this->challengeResultsFolders[$challenge0["id"]]['training_submission_folder_name'];  
             }
           echo '<option value="'.MIDAS_CHALLENGE_TRAINING.'">'.MIDAS_CHALLENGE_TRAINING.'</>';
           }
         echo '</select></td></tr>';
      
         echo         
        '<tr><td><h3>Submission Folder:</h3></td>';
        echo '<td><div id="midas_challenge_competitor_browseResultsFolder" class="genericBigButton ">';
        echo "<a  ><img  alt='' src='{$this->coreWebroot}/public/images/FileTree/directory.png'/>";
        echo 'Browse';
        echo "</a>";
        if(!$defaultFolderName) 
          {
          $defaultFolderName = 'Select your submission folder for Challenge & Dataset';    
          }
        echo '</div>'.
        '<span id="midas_challenge_competitor_selectedResultsFolder" style="padding-left: 15px;">'.$defaultFolderName.'</span>';
        echo '</td></tr>';
        
        echo '<tr><td><h3>Submission Scoreboard Display Name:</h3></td><td><input type="text" id="midas_challenge_competitor_submissionName" value="'.$this->userName.'"/></td></tr>';         
        
        echo '</table>'.
        '<input type="hidden" id="midas_challenge_competitor_selectedResultsFolderId" value="'.$defaultFolderId.'"/>';
        
        
        
        
        echo 
        '<br/>'.
        '<br/>'.
        '<b>Results Folder Validation:</b>' .
        '<span class="validateResultsFolder" id="validateResultsFolder_AllMatched" style="display:none">All results are matched.</span>'.
        '<span class="validateResultsFolder" id="validateResultsFolder_SomeMatched" style="display:none">Some results are mis-matched or missing.</span>'.
        '<span class="validateResultsFolder" id="validateResultsFolder_NoneMatched" style="display:none">No results are matched.</span>'.
        '<span class="validateResultsFolder" id="validateResultsFolder_Error" style="display:none">Error</span>'.
        '<div id="midas_challenge_competitor_validatedResultsFolder_Info"> </div>'.
        '<div id="midas_challenge_competitor_matchedItems_Info"> </div>';
        
        
        
        }
      else
        {    
        echo "<h4>{$this->t("No challenge is available")}.</h4>";
        }
       ?>
  </div>
  <div id="midas_challenge_competitor_score" class="viewSideBar">
    <div id="midas_challenge_competitor_scoreResults">
      <a id="midas_challenge_competitor_scoreResults_anchor" class="buttonScoreSubmissionDisabled">Submit Results</a>
      <img id="generatingJobs" alt=""  src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" />
    </div>
  </div>