<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<div>
 
  <div id="midasChallengeMetricName"><?php echo $this->metric->getMetricName(); ?></div><br/>
  <?php
  $description = $this->metric->getDescription();
  if(!empty($description))
    {
    echo '<div id="midasChallengeMetricDescription">'.$description.'</div><br/>';  
    }
  $lowestScoreBest = $this->metric->getLowestScoreBest();
  if($lowestScoreBest)
    {
    echo "A lower score is better (zero is best).<br/><br/>";  
    }
  else
    {
    echo "A higher score is better.<br/><br/>";  
    }
  $referenceLink = $this->metric->getReferenceLink();
  echo '<div style="padding: 20px; 0px; 20px; 0px;">';
  if(!empty($referenceLink))
    {
    echo '<div style="width: 103px; float: left; margin-left: 103px;" id="midasChallengeMetricReference"><a target="_blank" class="wikipedia" href="'.$referenceLink.'">reference</a></div>';
    }
  $sourceLink = $this->metric->getSourceLink();
  if(!empty($sourceLink))
    {
    echo '<div style="width: 103px; float: left;" id="midasChallengeMetricSource"><a target="_blank" class="github" href="'.$sourceLink.'">source code</a></div><br/>';  
    }
  echo "</div>";
  ?>
    
</div>
