<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

 
$this->headScript()->appendFile($this->coreWebroot . '/public/js/layout/jquery.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.tablesorter.min.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/competitor/competitor.showscore.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/competitor/competitor.updatescore.js');
$this->headScript()->appendFile($this->apiWebroot . '/public/js/common/common.ajaxapi.js');
?>

<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.tablesorter.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/competitor/competitor.showscore.css" />



<div id="showscores" class="viewMain" >
      <div class ="genericWrapperTopRight">
         <?php
          echo '<div style="float:right;margin-right:-200px;" class="genericBigButton ">';
            echo "<a  href='{$this->webroot}/user/userpage#ui-tabs-1'><img style='float:left;margin-right:2px;' alt='' src='{$this->coreWebroot}/public/images/icons/back.png'/>";
            echo $this->t('Back');  
            echo "</a>";
          echo '</div>';
          
        ?>
    </div>
<?php 
  echo '<h3>Results from '.$this->challengeName.', '.$this->resultsRun->getResultsType().' run on '. $this->resultsRun->getDate().'</h3>';
?>
    <table class="tablesorter" id="tablesorter_scores">
      <thead>
        <tr class="header">
        <?php
        foreach($this->tableHeaders as $header)
          {
          echo "<th class='scorecol'>".ucfirst($header)."</th>";
          }
        ?>
        </tr>
        </thead>
        <tbody>
          <?php       
            $stripeClasses = array('odd', 'even');
            $stripeClassInd = 0;
            foreach($this->tableData['results_rows'] as $subject => $scores)
              {
              echo "<tr class='resultsRow ".$stripeClasses[$stripeClassInd++ % 2]."'>";
              foreach($this->tableData_resultsColumns as $column)
                {
                $colVal = $scores[$column];
                echo "<td>".$colVal."</td>";
                }
              echo "</tr>";
              }
          ?> 
      </tbody>
    </table>
    <br/>
    </div>



