<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/


 
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.tablesorter.min.js');
$this->headScript()->appendFile($this->apiWebroot . '/public/js/common/common.ajaxapi.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/competitor/competitor.showscore.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.tablesorter.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/competitor/competitor.common.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/competitor/competitor.showscore.css" />


<div id="showscores" class="viewMain" >
    <div class="aboutThisPage" id="challengeCompetitorScoreAbout"><a class="informationAbout"/>Scoring details</a></div><br/>
    
    
<?php
  echo 'Submission '. $this->resultsRun->getSubmissionName() . ', results for <a href="' . $this->datasetFolderLink . '">' . $this->resultsRun->getResultsType() . ' dataset</a> of <a href="' . $this->challengeLink . '">' . $this->challengeName . '</a><br/>';
  echo 'Submitted at ' . $this->resultsRun->getDate() . ' by ' . $this->submitterEmail;
  echo '<div class="resultsLoading">Retrieving results <img alt="Loading..." src="'.$this->coreWebroot.'/public/images/icons/loading.gif" /></div>';
  echo '<div style="display: none;" class="resultsProcessing">Results are currently processing.<br/>When the results are complete, an email will be sent to the submitting user.</div>';
  echo '<div style="display: none;" class="resultsComplete">Results have completed processing.<br/>An email has been sent to the submitting user.</div>';
?>
    <table class="tablesorter" id="tablesorter_scores">
      <thead>
        <tr class="header">
        <?php
        $tableHeaders = $this->tableHeaders;
        foreach($tableHeaders as $header)
          {
          if(array_key_exists($header, $this->metricIds))
            {
            echo "<th class='scorecol midasChallengeMetricCol' id='challengeMetric_".$this->metricIds[$header]."' >".ucfirst($header)."</th>";
            }
          else
            {
            echo "<th class='scorecol'>".ucfirst($header)."</th>";
            }
          }
        ?>
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
    <br/>
    </div>



