<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>


  <div id="midas_challenge_competitor_troubleshooting" class="viewMain">
      
      For general information and an FAQ look to <a href="http://challenge.kitware.com/midas/">http://challenge.kitware.com/midas</a>
      
      <h3>ISBI 2013 Prostate Segmentation</h3>
      
      See the <a href="http://challenge.kitware.com/midas/community/5#tabs-info">ISBI 2013 Prostate Segmentation info page</a> for information.
      <p/>
                                                          
      Email <a href="mailto:challenge.isbi2013prostatesegmentation@kitware.com">challenge.isbi2013prostatesegmentation@kitware.com</a> with further questions.
      
      <h3>BRATS 2012</h3>
      
      See the <a href="http://challenge.kitware.com/midas/community/2#tabs-info">BRATS 2012 info page</a> for information.
      <p/>
                                                          
      Email <a href="mailto:challenge.brats2012@kitware.com">challenge.brats2012@kitware.com</a> with further questions.
  </div>