<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>


  <div id="midas_challenge_competitor_troubleshooting" class="viewMain">
      
      See the <a href="http://challenge.kitware.com/midasstaging/community/5#tabs-info">BRATS 2012 info page</a> for information and an <b>FAQ</b>.
      <p/>
                                                          
      
      If you have further questions, please email <a href="mailto:challenge.brats2012@kitware.com">challenge.brats2012@kitware.com</a> for support.
  </div>